USE SQL1;
SELECT NAME, SALARY
FROM EMPLOYEES
WHERE SALARY > (SELECT AVG(SALARY) FROM EMPLOYEES);

CREATE TABLE customers (
    customer_id INT PRIMARY KEY,
    customer_name VARCHAR(50)
);

-- Insert Sample Data
INSERT INTO customers (customer_id, customer_name) VALUES
(101, 'John Doe'),
(102, 'Jane Smith'),
(103, 'Alice Johnson'),
(104, NULL),
(105, 'Robert Brown');

-- 2 - CUSTOMER ORDERS WITHOUT MATCHING RECORDS.
SELECT  CUSTOMER_ID
FROM CUSTOMERS
WHERE CUSTOMER_NAME = NULL;

-- 3 - TOTAL SALES AMOUNT FOR EACH PRODUCT.
SELECT PRODUCT_NAME ,SUM(AMOUNT) AS TOTAL_SALES
FROM PRODUCTS
INNER JOIN SALES ON P.PRODUCT_ID = S.PRODUCT_ID
GROUP BY PRODUCT_NAME;

-- 4 - DEPARTMENT NAME WITH NO OF EMPLOYEES
SELECT DEPARTMENT_NAME , COUNT(EMPLOYEES) AS NUMBER_EMPLOYEES
FROM DEPARTMENTS
LEFT JOIN EMPLOYEES ON D.DEPARTMENT_ID = E.DEPARTMENT_ID
GROUP BY DEPARTMENT_NAME;

-- 5 - TOP 3 HIGHEST SALES 
SELECT sale_id, customer_id, amount, sale_date
FROM SALES
ORDER BY AMOUNT DESC
LIMIT 3;
